// Code generated by gencerts. DO NOT EDIT.

package certs

import _ "embed"

// CA Certificate
//go:embed ca.crt
var CACert string

//go:embed ca.key
var CAKey string

// Server Certificate
//go:embed server.crt
var ServerCert string

//go:embed server.key
var ServerKey string

// Agent Certificate
//go:embed agent.crt
var AgentCert string

//go:embed agent.key
var AgentKey string

// Implant Certificate
//go:embed implant.crt
var ImplantCert string

//go:embed implant.key
var ImplantKey string
