// Code generated by gencerts. DO NOT EDIT.

package certs

import _ "embed"

// CA Certificate
//go:embed ca.crt
var CACert string

//go:embed ca.key
var CAKey string

// Server Certificate
//go:embed server.crt
var ServerCert string

//go:embed server.key
var ServerKey string

// Client Certificate
//go:embed client.crt
var ClientCert string

//go:embed client.key
var ClientKey string

// Proxy Certificate
//go:embed proxy.crt
var ProxyCert string

//go:embed proxy.key
var ProxyKey string
