package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"network-tunneler/pkg/crypto"
)

var (
	org           string
	outputDir     string
	generateEmbed bool
)

func main() {
	rootCmd := &cobra.Command{
		Use:   "gencerts",
		Short: "Generate TLS certificates for network tunneler",
		Run:   run,
	}

	rootCmd.Flags().StringVar(&org, "org", "Network Tunneler", "Organization name")
	rootCmd.Flags().StringVar(&outputDir, "output", "internal/certs", "Output directory for certificates")
	rootCmd.Flags().BoolVar(&generateEmbed, "embed", true, "Generate Go file with embedded certificates")

	if err := rootCmd.Execute(); err != nil {
		os.Exit(1)
	}
}

func run(cmd *cobra.Command, args []string) {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create output directory: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generating CA...")
	ca, err := crypto.GenerateCA(org)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate CA: %v\n", err)
		os.Exit(1)
	}

	caPath := filepath.Join(outputDir, "ca.crt")
	caKeyPath := filepath.Join(outputDir, "ca.key")
	if err := ca.SaveToFiles(caPath, caKeyPath); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to save CA: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  CA certificate: %s\n", caPath)
	fmt.Printf("  CA private key: %s\n", caKeyPath)

	fmt.Println("\nGenerating server certificate...")
	serverCert, serverKey, err := crypto.GenerateCert(ca, crypto.CertOptions{
		CommonName: "server",
		DNSNames:   []string{"localhost", "server"},
		IPAddr:     []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")},
		Type:       crypto.ServerCert,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate server certificate: %v\n", err)
		os.Exit(1)
	}

	serverCertPath := filepath.Join(outputDir, "server.crt")
	serverKeyPath := filepath.Join(outputDir, "server.key")
	if err := crypto.SaveCert(serverCert, serverKey, serverCertPath, serverKeyPath); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to save server certificate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  Server certificate: %s\n", serverCertPath)
	fmt.Printf("  Server private key: %s\n", serverKeyPath)

	fmt.Println("\nGenerating agent certificate...")
	agentCert, agentKey, err := crypto.GenerateCert(ca, crypto.CertOptions{
		CommonName: "agent",
		DNSNames:   []string{"agent"},
		Type:       crypto.ClientCert,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate agent certificate: %v\n", err)
		os.Exit(1)
	}

	agentCertPath := filepath.Join(outputDir, "agent.crt")
	agentKeyPath := filepath.Join(outputDir, "agent.key")
	if err := crypto.SaveCert(agentCert, agentKey, agentCertPath, agentKeyPath); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to save agent certificate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  Agent certificate: %s\n", agentCertPath)
	fmt.Printf("  Agent private key: %s\n", agentKeyPath)

	fmt.Println("\nGenerating implant certificate...")
	implantCert, implantKey, err := crypto.GenerateCert(ca, crypto.CertOptions{
		CommonName: "implant",
		DNSNames:   []string{"implant"},
		Type:       crypto.ClientCert,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate implant certificate: %v\n", err)
		os.Exit(1)
	}

	implantCertPath := filepath.Join(outputDir, "implant.crt")
	implantKeyPath := filepath.Join(outputDir, "implant.key")
	if err := crypto.SaveCert(implantCert, implantKey, implantCertPath, implantKeyPath); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to save implant certificate: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  Implant certificate: %s\n", implantCertPath)
	fmt.Printf("  Implant private key: %s\n", implantKeyPath)

	fmt.Println("\nCertificates generated successfully!")
	fmt.Printf("\nAll certificates saved to: %s\n", outputDir)

	if generateEmbed {
		fmt.Println("\nGenerating Go embed file...")
		if err := generateEmbedFile(outputDir); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to generate embed file: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("  Go embed file: %s\n", filepath.Join(outputDir, "embed.go"))
	}

	fmt.Println("\nTo use embedded certificates, import:")
	fmt.Println("  import \"network-tunneler/internal/certs\"")
}

func generateEmbedFile(dir string) error {
	content := `// Code generated by gencerts. DO NOT EDIT.

package certs

import _ "embed"

// CA Certificate
//go:embed ca.crt
var CACert string

//go:embed ca.key
var CAKey string

// Server Certificate
//go:embed server.crt
var ServerCert string

//go:embed server.key
var ServerKey string

// Agent Certificate
//go:embed agent.crt
var AgentCert string

//go:embed agent.key
var AgentKey string

// Implant Certificate
//go:embed implant.crt
var ImplantCert string

//go:embed implant.key
var ImplantKey string
`

	embedPath := filepath.Join(dir, "embed.go")
	if err := os.WriteFile(embedPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write embed file: %w", err)
	}

	return nil
}
